// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// c da qoshish amali
class CService {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  CService(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  CService.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int addUsingC(
    int a,
    int b,
  ) {
    return _addUsingC(
      a,
      b,
    );
  }

  late final _addUsingCPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
          'addUsingC');
  late final _addUsingC = _addUsingCPtr.asFunction<int Function(int, int)>();

  ffi.Pointer<ffi.Char> get_hello_from_c() {
    return _get_hello_from_c();
  }

  late final _get_hello_from_cPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'get_hello_from_c');
  late final _get_hello_from_c =
      _get_hello_from_cPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();
}
